import mongoose, { Schema, Document, Types } from 'mongoose';

export type DomainStatus = 'active' | 'suspended';

export type DnsActivationStatus =
  | 'not_started'
  | 'activating'
  | 'active'
  | 'conflict'
  | 'activation_failed';

export interface IGeneratedDnsRecord {
  type: 'MX' | 'TXT' | 'CNAME';
  name: string;
  value: string;
  priority?: number | null;
  ttl?: number;
  purpose: string;
}

export interface IDnsConflictRecord {
  type: string;
  name: string;
  foundValue: string;
}

export interface IDomain extends Document {
  tenantId: Types.ObjectId;
  domainName: string;
  stalwartDomainId?: string | null;
  status: DomainStatus;
  mailboxLimit: number;
  employeeCount: number;
  isPrimary?: boolean;
  // The seat plan chosen at creation time; mailboxLimit/employeeCount above are
  // resolved from plan.seatCount server-side and remain the source of truth for
  // quota enforcement (mailbox.service.ts) — planId/planName are denormalized
  // for display/audit only, and stay valid even if the Plan is later archived.
  planId?: Types.ObjectId | null;
  planName?: string | null;

  // Domain DNS-activation lifecycle (GoDaddy + Stalwart provisioning).
  // Orthogonal to `status` above, which governs mail-service suspension only.
  dnsStatus: DnsActivationStatus;
  dnsRecords?: IGeneratedDnsRecord[];
  dnsConflicts?: IDnsConflictRecord[];
  // Raw BIND-style zone file text as generated by Stalwart itself (see
  // docs/STALWART_API_NOTES.md §7C). Captured for the "manual setup" path —
  // an admin/tenant can copy this wholesale into any DNS provider's zone
  // import feature instead of using one of the three automated integrations.
  dnsZoneFile?: string | null;
  dkimSelector?: string | null;
  dkimPublicKey?: string | null;
  dnsVerificationStartedAt?: Date | null;
  dnsLastCheckedAt?: Date | null;
  dnsVerifiedAt?: Date | null;
  activatedAt?: Date | null;

  createdAt: Date;
  updatedAt: Date;
}

const GeneratedDnsRecordSchema = new Schema<IGeneratedDnsRecord>(
  {
    type: { type: String, enum: ['MX', 'TXT', 'CNAME'], required: true },
    name: { type: String, required: true },
    value: { type: String, required: true },
    priority: { type: Number, default: null },
    ttl: { type: Number, default: 3600 },
    purpose: { type: String, required: true },
  },
  { _id: false }
);

const DnsConflictRecordSchema = new Schema<IDnsConflictRecord>(
  {
    type: { type: String, required: true },
    name: { type: String, required: true },
    foundValue: { type: String, required: true },
  },
  { _id: false }
);

const DomainSchema = new Schema<IDomain>(
  {
    tenantId: {
      type: Schema.Types.ObjectId,
      ref: 'Tenant',
      required: true,
      index: true,
    },
    domainName: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    stalwartDomainId: {
      type: String,
      default: null,
      index: true,
    },
    status: {
      type: String,
      enum: ['active', 'suspended'],
      default: 'active',
      index: true,
    },
    mailboxLimit: {
      type: Number,
      required: true,
      default: 10,
    },
    employeeCount: {
      type: Number,
      default: 10,
    },
    isPrimary: {
      type: Boolean,
      default: false,
    },
    planId: {
      type: Schema.Types.ObjectId,
      ref: 'Plan',
      default: null,
    },
    planName: {
      type: String,
      default: null,
    },
    dnsStatus: {
      type: String,
      enum: ['not_started', 'activating', 'active', 'conflict', 'activation_failed'],
      default: 'not_started',
      index: true,
    },
    dnsRecords: {
      type: [GeneratedDnsRecordSchema],
      default: undefined,
    },
    dnsConflicts: {
      type: [DnsConflictRecordSchema],
      default: undefined,
    },
    dnsZoneFile: {
      type: String,
      default: null,
    },
    dkimSelector: {
      type: String,
      default: null,
    },
    dkimPublicKey: {
      type: String,
      default: null,
    },
    dnsVerificationStartedAt: {
      type: Date,
      default: null,
    },
    dnsLastCheckedAt: {
      type: Date,
      default: null,
    },
    dnsVerifiedAt: {
      type: Date,
      default: null,
    },
    activatedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
    collection: 'domains',
  }
);

DomainSchema.index({ tenantId: 1, domainName: 1 });

export const DomainModel = mongoose.model<IDomain>('Domain', DomainSchema);
