import { config } from '../config';
import { StalwartDkimKey, StalwartDkimAlgorithm } from '../stalwart/types';
import { IGeneratedDnsRecord } from '../db/models/Domain';

/**
 * Builds the canonical, real DNS record set a tenant must publish for mail
 * to work — replacing the old hardcoded/fake placeholder that used to live
 * inline in tenant.routes.ts. DKIM records come from Stalwart's actual
 * auto-generated keys (see docs/STALWART_API_NOTES.md §7); MX/SPF/DMARC use
 * Toowix's own canonical policy rather than Stalwart's harsher auto-defaults
 * (Stalwart's own zone file uses `-all` SPF and immediate `p=reject` DMARC,
 * which are too strict to hand a brand-new customer domain — see §7C of
 * that doc for the full discrepancy writeup).
 *
 * This canonical policy is also documented for customers in
 * docs/DOMAIN_SETUP_GUIDE.md — keep the two in sync if either changes.
 */

const DKIM_ALGORITHM_LABEL: Record<StalwartDkimAlgorithm, string> = {
  Dkim1RsaSha256: 'rsa',
  Dkim1Ed25519Sha256: 'ed25519',
};

export function buildRequiredDnsRecords(domainName: string, dkimKeys: StalwartDkimKey[]): IGeneratedDnsRecord[] {
  const records: IGeneratedDnsRecord[] = [];
  const mailHost = config.mailHostname || 'mail.toowix.com';
  const ips = (config.mailServerIps || '103.13.114.138 103.13.114.227')
    .split(/\s+/)
    .filter(Boolean)
    .map((ip) => `ip4:${ip}`)
    .join(' ');

  records.push({
    type: 'MX',
    name: '@',
    value: mailHost,
    priority: 10,
    ttl: 3600,
    purpose: 'Primary Mail Routing Exchange',
  });

  records.push({
    type: 'TXT',
    name: '@',
    value: `v=spf1 mx ${ips} ~all`,
    ttl: 3600,
    purpose: 'Sender Policy Framework (SPF)',
  });

  for (const key of dkimKeys) {
    const algoLabel = DKIM_ALGORITHM_LABEL[key.algorithm] || key.algorithm.toLowerCase();
    records.push({
      type: 'TXT',
      name: `${key.selector}._domainkey`,
      value: `v=DKIM1; k=${algoLabel}; p=${key.publicKey}`,
      ttl: 3600,
      purpose: `DomainKeys Identified Mail (DKIM — ${algoLabel.toUpperCase()})`,
    });
  }

  records.push({
    type: 'TXT',
    name: '_dmarc',
    // Progressive rollout: start at p=none (monitor-only) for a newly activated
    // domain rather than quarantine/reject, to avoid silently dropping a new
    // customer's legitimate mail before they've confirmed SPF/DKIM alignment.
    value: `v=DMARC1; p=none; rua=mailto:dmarc-reports@${domainName}`,
    ttl: 3600,
    purpose: 'Domain-based Message Authentication Reporting (DMARC)',
  });

  return records;
}

/**
 * Renders the canonical record set above as BIND-style zone file text, for
 * the "Manual Setup" copy/export path. Deliberately built from the SAME
 * records buildRequiredDnsRecords() returns (and verifyPublicDns() checks
 * against) rather than from Stalwart's own auto-generated dnsZoneFile —
 * Stalwart's version uses a different, stricter SPF/DMARC policy and can
 * carry a stale/placeholder MX hostname (see docs/STALWART_API_NOTES.md
 * §7C), so a tenant who imported it verbatim could publish records that
 * this same backend would then never verify as active. Keeping one source
 * of truth means the zone file a tenant pastes always matches what's shown
 * in "Required DNS Records" and what verifyPublicDns() is checking for.
 */
export function buildZoneFileText(domainName: string, records: IGeneratedDnsRecord[]): string {
  const lines = [
    `; DNS zone records for ${domainName}`,
    `; Generated by Toowix Mail Platform — matches "Required DNS Records" exactly`,
  ];

  for (const record of records) {
    const fqdn = record.name === '@' ? `${domainName}.` : `${record.name}.${domainName}.`;
    const ttl = record.ttl || 3600;

    if (record.type === 'MX') {
      lines.push(`${fqdn}\t${ttl}\tIN\tMX\t${record.priority} ${record.value}.`);
    } else if (record.type === 'CNAME') {
      lines.push(`${fqdn}\t${ttl}\tIN\tCNAME\t${record.value}.`);
    } else {
      lines.push(`${fqdn}\t${ttl}\tIN\tTXT\t"${record.value}"`);
    }
  }

  return lines.join('\n');
}
